---
title: "Symposium Highlighting Evidence-Based Interventions for Addressing the Underrepresentation of Women in STEM"
description: |
  A short description of the post.
author:
  - name: Foong Yan LEE
    email: foongyan@uoregon.edu
date: 05-28-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


The National Academy of Sciences has been working on improving the underrepresentation of women in the field of STEM. This project has been running for 18 months by ad hoc committee. The recent symposium on 11 March 2019 was aimed to identify institutional barriers that stifle the representation of women in this field. The agenda was made up of four main sessions: Beyond Bias Panel, Family Friendly Policies, Recruitment, Retention and Advancement and National Programs. 

The Beyond Bias Panel was focusing on institutional strategies and processes for combating bias. Eve Fine, Associate Scientist and Director of Curriculum Development and Implementation, WISELI, University of Winconsin-Madison presented evidence-based strategies that reduced bias by breaking the habit. These included workshops for committees in the faculty, climate workshops for departmental chairs and bias literacy workshop that were designed to solve gender bias while encourage inclusion and diversity. A survey had been conducted after the intervention to study faculty work life. It found that there was significant improvement in the comfort of raising personal/family issues that conflicted with departmental activities by both men and women. Also, the experimental department (compared to control department) showed increased number of women being hired after 2 years (from 32% in 2010 to 47% in 2012). This research revealed that addressing bias as a habit of mind can change individual behaviors.

For many excellent articles on the topic of academic work/life and it's effects on climate, as well as, articles of strategies for improving diversity recruitment see: 
https://wiseli.wisc.edu/research/sfw/


The second panel- Family Friendly Policies was concentrating on the impact of tenure policies, parental leave, child care provision, dual career hiring and etc. Mia Ong, Panelist Senior Research Scientist TERC cited the continuous low number of women of color in STEM and its potential to raise social justice issues in United States.  The ideal workforce norm like gender division in the aspects of paid work and family life has posed further challenge for women’s participation in the field. Aside from this, women of color are prone to isolation, exclusion and racial inequalities. Mia suggested that to curb this phenomenon, we should have different norms for what constitute an ideal worker, enforce training for culturally competent mentoring, implement stricter policies against harassment and discrimination as well as funding more research on women of color in STEM industry. 
https://www.terc.edu/display/Staff/Mia+Ong

The third panel- Recruitment, Retention, and Advancement was about programs and policies aimed at improving the representation of women students and faculty. Alice Agogino from University of California Berkeley had presented the 2017-18 pilot initiative in the Engineering faculty of UC Berkeley. The goals were to improve the faculty hiring process (that less favored women and underrepresented minority) and to cultivate the culture in advancing equity and inclusion. The outcome for this was terrific as there was revised hiring guidelines to align with the diversity goal. For year 2018-19, the faculty plans to implement bias training, utilize diversity, equity and inclusion rubrics and to ingrain the spirit of implementation by having dialog and input.
https://me.berkeley.edu/people/alice-m-agogino/

Last but not least, the National Programs was a highlight on programs in scientific agencies and foundations that thrive on women’s representation. Janine Clayton, NIH Associate Director for Research on Women’s Health presented the initiative by NIH to improve women representation in STEM. Besides introducing family friendly policies, NIH sponsored research on identifying causes and intervention to support women in science. Also, NIH built a network that advances women as scientists called Women of Color Research Network (WoCRN). The institution assisted in barriers faced by women in biomedical research by forming mentoring network and working group that curb sexual harassment. NIH has strategic plans for women’s health research which comprised of more comprehensive research methods, better dissemination of data and promotion of training and career that advance science. 
https://orwh.od.nih.gov/about/director/bio
https://womeninscience.nih.gov/women-of-color/

In conclusion, despite the current underrepresentation of women (of color) in STEM, we have seen strategies that are both pipelined and ongoing from numerous institutions in tackling this issue. Changes will definitely take time, but efforts should bear fruits with persistent actions.   
 


